openapi: 3.1.0
x-stoplight:
  id: ys5yq9karz340
info:
  title: PaymentApi
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /submitOrder:
    parameters: []
    get:
      summary: Generate Order Reference Id
      tags: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                orderRefNumber:
                  value:
                    FL110000001: string
        '500':
          description: Internal Server Error
      operationId: submitorder
      description: This API is used to generate Order refernce number
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
          application/xml:
            schema:
              type: object
              properties: {}
            examples:
              PositiveScenerio:
                value: |-
                  {
                    "orderType": "INSTALL",
                    "serviceType": "DATA",
                    "stateCode": "FL"
                  }
        description: ''
  '':
    parameters: []
components:
  schemas:
    User:
      type: string
