openapi: 3.1.0
x-stoplight:
  id: ys5yq9karz340
info:
  title: SubmitOrder
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /submitOrder:
    parameters: []
    post:
      summary: Generate Order Reference Id
      operationId: post-submitOrder
      responses:
        '200':
          description: Response give us Order reference number.
          content:
            application/json:
              schema:
                type: object
                properties:
                  FL110000001:
                    type: string
                x-examples:
                  example-1:
                    FL110000001: string
              examples:
                example-1:
                  value:
                    FL110000001: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                orderType:
                  type: string
                serviceType:
                  type: string
                stateCode:
                  type: string
              x-examples:
                example-1:
                  orderType: INSTALL
                  serviceType: DATA
                  stateCode: FL
            examples:
              example-1:
                value:
                  orderType: string
                  serviceType: string
                  stateCode: string
      description: This API is used to generate Order refernce number
components:
  schemas:
    User:
      type: object
      properties:
        orderType:
          type: string
        serviceType:
          type: string
        stateCode:
          type: string
      x-examples:
        example-1:
          orderType: INSTALL
          serviceType: DATA
          stateCode: FL
      title: Generate Order Reference
      examples:
        - orderType: string
          serviceType: string
          stateCode: string
