openapi: 3.1.0
info:
  title: ServiceQualification
  version: '1.0'
  summary: Service Qualification API
  description: 'Service Qualification API is used to validate the address qualification, if address is qualified need to call pending order api to check address is having existing service or not'
  contact:
    name: Gaurav
    email: gaurav.khandelwal@brightspeed.com
servers:
  - url: 'https://brightspeed-np-dev.apigee.net'
paths:
  /dev-address-qualification:
    parameters: []
    get:
      summary: Service Avalibility
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                AddressQualified:
                  value:
                    errorCode: 0
                    errorText: Success
                    fullAddress: 910 FIRST ST Manteo NC 27954
                    addressId: null
                    latitude: null
                    longitude: null
                    brightSpeedFiberIndicator: Not available
                    interval: ''
                InValidAddress:
                  value:
                    errorCode: 3003
                    errorText: Invalid Address
                    fullAddress: 910 FIRST ST Manteo NC 27954
                    addressId: null
                    latitude: null
                    longitude: null
                    brightSpeedFiberIndicator: Not available
                    interval: ''
                ExistingService:
                  value:
                    errorCode: 3001
                    errorText: Active service available
                    fullAddress: 910 FIRST ST Manteo NC 27954
                    addressId: null
                    latitude: null
                    longitude: null
                    brightSpeedFiberIndicator: Not available
                    interval: ''
                ExistingInactiveService:
                  value:
                    errorCode: 3002
                    errorText: Service is available but Inactive
                    fullAddress: 910 FIRST ST Manteo NC 27954
                    addressId: null
                    latitude: null
                    longitude: null
                    brightSpeedFiberIndicator: Not available
                    interval: ''
        '201':
          description: Created
        '404':
          description: User Not Found
      operationId: ''
      description: Used to check service availibility
      parameters:
        - schema:
            type: string
          in: query
          name: addressLine1
          description: Full address
        - schema:
            type: string
          in: header
          name: Authorization
  '':
    parameters: []
components:
  schemas:
    User:
      title: ServiceQualification
      type: object
      description: ''
      examples:
        - errorCode: 0
          errorText: Success
          fullAddress: 910 FIRST ST Manteo NC 27954
          addressId: null
          latitude: null
          longitude: null
          brightSpeedFiberIndicator: Not available
          interval: ''
      properties:
        addressLine1:
          type: string
