openapi: 3.1.0
info:
  title: ServiceQualification
  version: '1.0'
  summary: Service Qualification API
  description: 'Service Qualification API is used to validate the address qualification, if address is qualified need to call pending order api to check address is having existing service or not'
  contact:
    name: Gaurav
    email: gaurav.khandelwal@brightspeed.com
servers:
  - url: 'https://brightspeed-np-dev.apigee.net'
paths:
  /dev-address-qualification:
    parameters: []
    get:
      summary: Service Avalibility
      tags: []
      responses:
        '200':
          description: Different response based on scenerio.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                AddressQualified:
                  value:
                    fullAddress: '404 Sir Walker Ln Cary, NC, 27519'
                    addressId: '13579'
                    latitude: '35.906269'
                    longitude: '-75.671181'
                    brightSpeedFiberIndicator: QUALIFIED
                    interval: +1 day
                    existingService: false
                    pendingOrder: false
                    streetNumber: ''
                    streetName: SIR WALKER LN
                    streetSuffix: LN
                    postalCode: '27519'
                    city: CARY
                    state: NC
                    country: USA
                    addressSqft: '1938.0'
                    bedrooms: '3.0'
                    errorCode: '0'
                    errorText: Success
                    content:
                      header:
                        url: 'https://images.contentstack.io/v3/assets/bltae235e99a6dd6f85/blt68ad193519f2d750/629e33e2b86a794d785d52f3/Brightspeed_Logo_Full.png'
                      footer:
                        legal_menu:
                          form_buttons:
                            - button_label: Legal Notice
                              _metadata:
                                uid: cs098cb4418d294fc6
                              button_theme: Link
                              url: 'https://brspd-dev.brightspeed.com/about-us'
                              open_in_new_tab: true
                            - button_label: Privacy policy
                              _metadata:
                                uid: cs102d67b38c8afcd9
                              button_theme: Link
                              url: /about-us
                              open_in_new_tab: true
                            - button_label: Cookie Settings
                              _metadata:
                                uid: cs60e331f0aa65102e
                              button_theme: Link
                              url: /about-us
                              open_in_new_tab: true
                        logo:
                          url: 'https://images.contentstack.io/v3/assets/bltae235e99a6dd6f85/blt68ad193519f2d750/629e33e2b86a794d785d52f3/Brightspeed_Logo_Full.png'
                        social_menu:
                          - icon:
                              url: 'https://images.contentstack.io/v3/assets/bltae235e99a6dd6f85/blt5cddfeefabc4ef08/62a0c0bdce3d8856b19f887c/Twitter.png'
                            url: 'https://twitter.com/brightspeed'
                          - icon:
                              url: 'https://images.contentstack.io/v3/assets/bltae235e99a6dd6f85/blt8b4b67eed5035117/62a0c0e91944ac5ac425eac7/Facebook.png'
                            url: 'https://www.facebook.com/brightspeed'
                          - icon:
                              url: 'https://images.contentstack.io/v3/assets/bltae235e99a6dd6f85/blt69e3ed12c805f2b4/62a0c0fa44e495573d55ff8a/LinkedIn.png'
                            url: 'https://www.linkedin.com/brightspeed'
                      content:
                        availability_form:
                          heading: How fast do you want to go ?
                          checkbox: ACP (Affordable Connectivity Program)
                          input_field: Street Address
                          subheading: Enter your address to check availability
                        form_button:
                          form_buttons:
                            - button_label: Back
                              _metadata:
                                uid: cscca27a35022d60a1
                              button_theme: Black
                              url: /
                              open_in_new_tab: false
                            - button_label: Continue
                              _metadata:
                                uid: csbfb5118dab6bcda2
                              button_theme: Yellow
                              url: /voip-products
                              open_in_new_tab: false
                        headline: How fast do you want to go ?
                InValidAddress:
                  value:
                    errorCode: 3003
                    errorText: Invalid Address
                    fullAddress: ''
                    addressId: ''
                    latitude: ''
                    longitude: ''
                    brightSpeedFiberIndicator: Not Qualified
                    interval: ''
                    existingService: false
                    pendingOrder: false
                ExistingService:
                  value:
                    errorCode: 3001
                    errorText: Active service available
                    fullAddress: 940 FIRST ST MANTEO NC 27954
                    addressId: 40b73544650ab176bad928638e341ed2
                    latitude: '35.91777'
                    longitude: '-75.679993'
                    brightSpeedFiberIndicator: Qualified
                    interval: +1 day
                    existingService: true
                    pendingOrder: false
        '201':
          description: Created
        '400':
          description: Bad Request
        '404':
          description: User Not Found
      operationId: ''
      description: Used to check service availibility
      parameters:
        - schema:
            type: string
          in: query
          name: addressLine1
          description: Full address
        - schema:
            type: string
          in: header
          name: Authorization
components:
  schemas:
    User:
      type: object
      properties:
        errorCode:
          type: integer
        errorText:
          type: string
        fullAddress:
          type: string
        addressId:
          type: string
        latitude:
          type: string
        longitude:
          type: string
        brightSpeedFiberIndicator:
          type: string
        interval:
          type: string
        existingService:
          type: boolean
        pendingOrder:
          type: boolean
      x-examples:
        example-1:
          errorCode: 0
          errorText: Success
          fullAddress: 940 FIRST ST MANTEO NC 27954
          addressId: 40b73544650ab176bad928638e341ed2
          latitude: '35.91777'
          longitude: '-75.679993'
          brightSpeedFiberIndicator: Qualified
          interval: +1 day
          existingService: false
          pendingOrder: false
