openapi: 3.1.0
x-stoplight:
  id: lkslbg9vacwxk
info:
  title: SessionManagement
  version: '1.0'
  summary: This API is used to generate session id to track the user
servers:
  - url: 'http://localhost:3000'
paths:
  getSessionId:
    parameters: []
    get:
      summary: This API is used to generate session id
      tags: []
      operationId: getSessionId
      description: This API is used to generate session id to track the user
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionId:
                    type: string
                x-examples:
                  example-1:
                    sessionId: 87872287-7d7d-8u8u-9d9s-7776789hjd8d
              examples:
                example-1:
                  value:
                    sessionId: 87872287-7d7d-8u8u-9d9s-7776789hjd8d
components:
  schemas:
    User:
      title: SessionId
      type: object
      description: ''
      examples:
        - session: 87872287-7d7d-8u8u-9d9s-7776789hjd8d
      properties:
        session:
          type: string
      required:
        - session
