openapi: 3.1.0
x-stoplight:
  id: lkslbg9vacwxk
info:
  title: SessionManagement
  version: '1.0'
  summary: This API is used to generate session id to track the user
servers:
  - url: 'http://localhost:3000'
paths:
  getSessionId:
    parameters: []
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  example-1:
                    session: string
                properties:
                  session:
                    type: string
              examples:
                sessionid:
                  value:
                    session: 87872287-7d7d-8u8u-9d9s-7776789hjd8d
        '404':
          description: User Not Found
        '':
          description: Give as session id
          content:
            application/json:
              schema:
                type: object
                properties:
                  session:
                    type: string
                x-examples:
                  example-1:
                    session: string
              examples:
                sessionid:
                  value:
                    session: 87182711-3c9e-4f91-8bc1-333345g12b5g
      operationId: get-users-userId
      description: 'This API is used create session id fro tracking user action. '
components:
  schemas:
    User:
      title: SessionId
      type: object
      description: ''
      examples:
        - session: 87872287-7d7d-8u8u-9d9s-7776789hjd8d
      properties:
        session:
          type: string
      required:
        - session
